### ISSUE TITLE
Auto rain joiner request

### ISSUE THREAD

**Issue by DaKingOfAllDaSkidz** [Aspectise/Bloxflip-auto-tools#2]
I am begging you to add the auto rain joiner

**Comment by NotValra** [comment]
Thats almost impossible unless u have a hcaptcha solver

**Comment by Aspectise** [comment]
As Valra mentioned, an hCaptcha solver key is required to join Bloxflip rains

**Comment by DaKingOfAllDaSkidz** [comment]
I have 2 hCaptcha solvers and one recapcha but i think it does work

**Comment by DaKingOfAllDaSkidz** [comment]
I mean doesn't
