### ISSUE TITLE
crash and slides not working

### ISSUE THREAD

**Issue by ratfucker63** [Aspectise/Bloxflip-auto-tools#4]
when i do crash or slides it just becomes black with only the title there, i tried other modes and they work fine. i tried to wait for a min and then it crashes 
![image_2024-07-25_102620847](https://github.com/user-attachments/assets/c52d4010-aa3e-4552-a7b3-ffa9efa41163)

**Comment by THXDUST** [comment]
Sadly, this does not have a way to fix, the method that he used was too old and bloxflip noticed it and made a way to stop it from working.
In other words, the api method used in this project stopped working due to changes in crash and slide inner api.

**Comment by Aspectise** [comment]
Bloxflip upgraded there websocket cloudflare security which broke crash and slides
